version: '3'
services:
  bodypix:
    build: bodypix
    image: bodypix
    restart: unless-stopped
    init: true
    runtime: nvidia

  fakecam:
    build: fakecam
    image: fakecam
    restart: unless-stopped
    init: true
    user: '1000:986'
    environment:
      MASK_PERSIST_FRAME_COUNT: '1'
    devices:
      - '/dev/video0:/dev/video0'
      - '/dev/video9:/dev/video9'
      - '/dev/video10:/dev/video10'
